server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;
    username: sa
    password:
  thymeleaf:
    suffix: .html
mybatis:
  type-aliases-package: first.project.todolist.todolist.dto

